# Generated by Django 4.1.2 on 2022-11-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='stuffs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping.staff'),
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(blank=True, max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.CharField(blank=True, max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping.profession'),
        ),
    ]
